apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "updating port to 110"
  name: test-deployment
  labels:
    app: test-deployment
spec:
  revisionHistoryLimit: 10
  replicas: 3
  selector:
    matchLabels:
      app: app
      env: dev
  template:
    metadata:
      labels:
        app: app
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 110