apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
      env: dev
  template:
    metadata:
      labels:
        app: app
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest