apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "updating port to 110"
  name: nginx-deployment
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 10
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    env: dev
spec:
  type: NodePort
  selector:
    app: nginx # el del pod
    env: dev # del pod
  ports:
    - protocol: TCP
      port: 8090 # PUERTO DEL SERVICIO
      targetPort: 80 # PUERTO DEL POD