apiVersion: v1
kind: Pod
metadata:
  name: doscont
  labels:
    app: doscont
spec:
  containers:
  - name: cont1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo "cont1" > indext.html && python -m http.server 8081']
  - name: cont2
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo "cont2" > indext.html && python -m http.server 8082']
  # - name: cont3
  #   image: nginx:alpine