apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  labels:
    app: dev-pod
    environment: dev
    namespace: default
spec:
  containers:
  - name: cont1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo "cont1" > indext.html && python -m http.server 80']
  - name: cont2
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo "cont2" > indext.html && python -m http.server 8082']
---
apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
  labels:
    app: prod-pod
    environment: prod
    namespace: default
spec:
  containers:
  - name: cont1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo "cont1" > indext.html && python -m http.server 8081']
  - name: cont2
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo "cont2" > indext.html && python -m http.server 8082']